### ISSUE TITLE
Build Failed.

### ISSUE THREAD

**Issue by Aria461863631** [jedisct1/wasm-crypto#12]
Hi, I tried to build this project but failed in many ways.
Can anybody help me please....

---

First I tried to clone this repo, run `npm install` then `npm run asbuild`
I got 
```shell
Error: Error: Cannot find module 'typescript'
Error: Cannot find module './assemblyscript'
```

---

So I tried to modify `package.json`  
I change `"assemblyscript": "github:AssemblyScript/assemblyscript"` to `"assemblyscript": "^0.9.2"` before install, but it still failed with
```shell
> asc assembly/crypto.ts assembly/precomp.ts -b build/optimized.wasm -t build/optimized.wat --sourceMap --validate -O3

RangeError: Maximum call stack size exceeded
...
abort(RangeError: Maximum call stack size exceeded). Build with -s ASSERTIONS=1 for more info.
```

but it success when running `npm run asbuild:untouched` and `npm run asbuild:small`
I also run `npm run test` but got stuck at `[Describe]: hashing`

---

When I use `untouched.wasm` in web I got an error
```
107 Uncaught (in promise) TypeError: memory_allocate is not a function
```

I'm really a newbie in webassembly and typescript
I finally succeed using the `optimized.wasm` inside the `access_control_example` with its loader and way of calling functions. Thanks for that!
I just still confused by the compiling error.

**Comment by jedisct1** [comment]
It's not you :)

Try again, it should now be way easier to build.
