### ISSUE TITLE
import into assemblyscript project

### ISSUE THREAD

**Issue by tbrannam** [jedisct1/wasm-crypto#36]
I'm working on an assemblyscript port - and was in search of crypto routines - this looks promising, but it seems that it's not possible to import these into a web-assembly project?  are these meant only to be called/hosted from a javascript app?

**Comment by jedisct1** [comment]
Hi!

I'm a little bit confused here.

That project is written in AssemblyScript, so it can be used in AssemblyScript. Just add the files to your project :)

**Comment by tbrannam** [comment]
Makes sense to me, just having some issues where it is failing to resolve
the import in my aspect spec file... I will dig deeper.   Still at the
enthustiatic beginner phase.

Thanks
